{{- if .Values.ngcSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ngcSecret.name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.ngcSecret.dockerConfigJson }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nim-secrets
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  ngc-api-key: {{ .Values.global.nvidiaApiKey | quote }}
